# Generated by Django 5.1.7 on 2025-03-06 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='entry',
            table='Entradas',
        ),
        migrations.AlterModelTable(
            name='exit',
            table='Saídas',
        ),
    ]
